version: "3.9"

services:
  basededatos:
    build: .
    ports:
      - "2000:5000"
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db
  
  sebastian:
    build: 
      context: /Sebastian
      dockerfile: /Sebastian/Dockerfile
    ports:
      - "3000:5000"
    volumes:
      - ../:/app
      - ./db/:/my/sqlite/path/
    