version: "3.9"

services:
  basededatos:
    build: .    
    stdin_open: true
    tty: true
    volumes:
      - "db:/db"
  
  sebastian:
    build: 
      context: /Sebastian
      dockerfile: /Dockerfile 
    volumes:      
      - "db:/db"
    

  api-gateway:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - sebastian
    ports:
      - "5000:80"
volumes:
  db: