version: "3.9"

services:
  
  basededatos:
    build: .    
    stdin_open: true
    tty: true
    volumes:
      - db:/app/db
  
  sebastian:
    build: 
      context: ./HU_3_HU_4
      dockerfile: /Dockerfile 
    volumes:      
      - db:/app/db

  reinaldo:
    build: 
      context: ./HU_1_HU_2
      dockerfile: /Dockerfile 
    volumes:      
      - db:/app/db

  helena:
    build: 
      context: ./HU_6_HU_7
      dockerfile: /Dockerfile 
    volumes:      
      - db:/app/db

  sonia:
    build: 
      context: ./HU_8_HU_9
      dockerfile: /Dockerfile 
    volumes:      
      - db:/app/db
    

  api-gateway:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - sebastian
      - reinaldo
      - helena
      - sonia
    ports:
      - "4000:80"
volumes:
  db: